#pragma once

#ifndef GRAPHENGINE_NAMESPACE_H_
#define GRAPHENGINE_NAMESPACE_H_

#ifndef GRAPHENGINE_IMPL_NAMESPACE
  #define GRAPHENGINE_IMPL_NAMESPACE impl
#endif

#endif // GRAPHENGINE_NAMESPACE_H_
